# Generated by Django 2.2 on 2019-04-08 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.BooleanField(choices=[(1, 'Autumn'), (0, 'Spring')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taken_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaching_assistants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assisted_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
