# Generated by Django 2.2 on 2019-04-08 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_admin', '0002_auto_20190408_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admins',
        ),
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='taken_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='teaching_assistants',
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(related_name='assisted_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
